version: '3.1'
services:
  stats-server:
    build: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SERVER_PORT=9090
      - DB_NAME=explore-with-me-stat
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - DB_HOST=stats-server-db
      - DB_PORT=5432
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore-with-me-stat

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=enw-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - .:/docker-entrypoint-initdb.d

  ewm-service:
    build: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SERVER_PORT=8080
      - DB_NAME=explore-with-me
      - EXPLORE_WITH_ME_URL=http://stats-server:9090
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/enw-main-service

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=enw-main-service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - .:/docker-entrypoint-initdb.d