version: '3.1'
services:
  stats-server:
    build: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/enw-stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - POSTGRES_DB=enw-stats

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=enw-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - .:/docker-entrypoint-initdb.d

  ewm-service:
    build: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/enw-main-service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - POSTGRES_DB=enw_main_service
      - EXPLORE_WITH_ME_STATS_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: enw-main-service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=enw-main-service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - .:/docker-entrypoint-initdb.d