DROP TABLE IF EXISTS  stat CASCADE;

CREATE TABLE IF NOT EXISTS stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    app     VARCHAR(100),
    uri     VARCHAR(100),
    ip      VARCHAR(100),
    TIMESTAMP timestamp with time zone,
    CONSTRAINT stat_pk PRIMARY KEY (id)
);